const argomenti = [
    'Sport',
    'Cantanti',
    'Nomi canzoni',
    'Film',
    'Serie TV',
    'Nazioni',
    'Calciatori',
    'Personaggi dello spettacolo',
    'Elementi della tavola periodica',
    'Artisti famosi',
    'Strumenti musicali',
    'Libri',
    'Celebrità storiche',
    'Cartoni animati',
    'Piatti e ricette',
    'Animali',
    'Tutto ciò che riguarda lo spazio',
    'Mestieri',
    'Automobili',
    'Personaggi mitologici',
    'Giochi',
    'Città italiane',
    'Città pugliesi',
    'Mezzi di trasporto',
    'Frutta',
    'Forme geometriche',
    'Fiori',
    'Formaggi',
    'Oggetti da scrvania',
    'Festività e ricorrenze',
    'Personaggi dei cartoni animati',
    'Mezzi di comunicazione',
    'Prodotti da bagno',
    'Abbigliamento',
    'Marchi di abbigliamento',
    'Marchi di tecnologia',
    'Prodotti per la scuola'
];

export default argomenti